---
version: "3.7"

services:
  web:
    build:
      cache_from:
        - docker.pkg.github.com/ne-sachirou/sifaru_yusin_radical_generator/web:latest
      context: .
      dockerfile: Dockerfile
    depends_on: [web-src]
    image: docker.pkg.github.com/ne-sachirou/sifaru_yusin_radical_generator/web:latest
    logging:
      options:
        max-size: "10m"
        max-file: "2"
    ports:
      - 5000:5000
    volumes:
      - web-src:/mnt

  web-src:
    image: eugenmayer/unison:2.51.2.2
    environment:
      APP_VOLUME: /app_sync
      HOST_VOLUME: /host_sync
      TZ: Asia/Tokyo
      UNISON_ARGS: |
        -debug default -prefer /host_sync -numericids -auto -batch -fat \
        -ignore 'Name .#*' \
        -ignore 'Name .git/*' \
        -ignore 'Name .venv/*' \
        -ignore 'Name __target__/*' \
        -ignore 'Name node_modules/*' \
      UNISON_DEST: /app_sync
      UNISON_SRC: /host_sync
      UNISON_WATCH_ARGS: "-repeat watch"
    logging:
      options:
        max-size: "10m"
        max-file: "2"
    volumes:
      - ${PWD:-.}/web-src/src-entrypoints:/docker-entrypoint.d/:ro
      - ${PWD:-.}/web-src/supervisor.conf.d:/etc/supervisor.conf.d:ro
      - ${PWD:-.}:/host_sync:cached
      - web-src:/app_sync

volumes:
  web-src:
