---
name: Deploy GitHub Pages
"on":
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
      pages: write
    env:
      ANTLR4_VERSION: "4.13.2"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 21

      - name: Install ANTLR4
        # yamllint disable rule:line-length
        run: |
          sudo apt-get install -y --no-install-recommends curl
          curl -fsSL "https://www.antlr.org/download/antlr-${ANTLR4_VERSION}-complete.jar" > "antlr-${ANTLR4_VERSION}-complete.jar"
        # yamllint enable rule:line-length
        working-directory: packages/sifaru_yusin

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build ui
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
